print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade: int = int(input("Quantos anos você tem? "))
print(f"{nome} tem {idade} anos")
nacionalidade:str = input("Qual é a sua nacionalidade? ")
print(f"{nome} tem {idade} anos e {nacionalidade}")
